[theme]
primaryColor = "#4F46E5"
backgroundColor = "#F1F5F9"
secondaryBackgroundColor = "#E2E8F0"
textColor = "#0F172A"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
